defaults:
  - _self_
  - training: training.yaml
  - model: egnn.yaml
  - optimizer: adamw.yaml 
  - data: shapenet.yaml

accelerator: "gpu"
devices: 1



hydra:
  sweeper:
    params:
      training.batch_size: 256,512
      training.barlow_lambda: 1e-6,1e-5,1e-3,1e-2
      optimizer.learning_rate: 5e-6,5e-4
      model.encoder_depth: 1,2,3
      model.encoder_init_feat_dim: 32,128,256
      model.encoder_out_feat_dim: 256,1024
