# Data and logging
model_weights: "results/best_model_delta_t_0.01.pth"
training_dir: "/mnt/jonathan/DataFlowMatching/small_training_data" #"/mnt/justin/training_data/" # #  "/mnt/justin/small_data/"  
log_dir: "log/"

# General parameters
num_epochs: 1000
batch_size: 8


max_points: 150
time_step: 5e-2
load_model: False

cont: False 
model_checkpoint: null 
test: False 
hparams: null 

# Losses 
pair_loss: False
recon_loss: True 
consistency_loss: True 
sparse_loss: False
sparsity_weight: 0.0
recon_weight: 0.5
consistency_weight: 0.5
barlow_weight: 0.0
denoise_input: False


# Barlow
barlow_lambda: 1e-6

# Consistency augmentation
num_lowres_augmentations: 32
min_radius: 0.1
max_radius: 0.75
svm_batch_size: 256 # do the max RAM allows since not used for gradients + batches are to be accumulated... 